allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  esbuild: true
  msedge-tts: true
  protobufjs: true
onlyBuiltDependencies:
  - "@firebase/util"
  - "@google/genai"
  - esbuild
  - protobufjs
